# Generated by Django 2.1.7 on 2019-03-27 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
        ('ideas_app', '0002_auto_20190327_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messages_app.Attachment')),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='attachment',
            field=models.ManyToManyField(blank=True, related_name='note_attachment', through='ideas_app.NoteAttachment', to='messages_app.Attachment'),
        ),
        migrations.AddField(
            model_name='noteattachment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas_app.Note'),
        ),
    ]
