# Generated by Django 2.1.7 on 2019-05-26 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(default='derp', max_length=100)),
                ('surname', models.CharField(default='derpington', max_length=100)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('REG', 'Regular employee'), ('MAN', 'Project manager')], default='Regular employee', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proffession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proffession_name', models.CharField(max_length=20)),
                ('proffession_description', models.TextField(blank=True, default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('token', models.CharField(max_length=5)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2019, 5, 27, 15, 3, 23, 411797))),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='proffession',
            field=models.ManyToManyField(to='users_app.Proffession'),
        ),
    ]
