# Generated by Django 2.1.7 on 2019-03-27 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 23, 7, 27, 352732)),
        ),
    ]
