# Generated by Django 2.1.7 on 2019-03-31 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordtoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 21, 12, 28, 782313)),
        ),
    ]
