# Generated by Django 2.1.7 on 2019-03-04 23:21

from django.db import migrations, models
import django.utils.timezone
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proffession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proffession_name', models.CharField(choices=[(users_app.models.Proffessions('Not assigned'), 'Not assigned'), (users_app.models.Proffessions('Programmer'), 'Programmer'), (users_app.models.Proffessions('Tester'), 'Tester'), (users_app.models.Proffessions('Project manager'), 'Project manager'), (users_app.models.Proffessions('System architect'), 'System architect'), (users_app.models.Proffessions('System administrator'), 'System administrator')], default=users_app.models.Proffessions('Not assigned'), max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(users_app.models.UserRoles('Regular employee'), 'Regular employee'), (users_app.models.UserRoles('Project manager'), 'Project manager')], default=users_app.models.UserRoles('Regular employee'), max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='proffession',
            field=models.ManyToManyField(to='users_app.Proffession'),
        ),
    ]
