# Generated by Django 2.1.7 on 2019-03-04 23:35

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20190304_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proffession',
            name='proffession_name',
            field=models.CharField(choices=[(users_app.models.Proffessions('Not assigned'), 'Not assigned'), (users_app.models.Proffessions('Programmer'), 'Programmer'), (users_app.models.Proffessions('Tester'), 'Tester'), (users_app.models.Proffessions('Project manager'), 'Project manager'), (users_app.models.Proffessions('System architect'), 'System architect'), (users_app.models.Proffessions('System administrator'), 'System administrator')], max_length=15),
        ),
    ]
