# Generated by Django 2.1.7 on 2019-03-09 12:22

from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20190304_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proffession',
            name='proffession_name',
            field=models.CharField(choices=[('NONE', 'Not assigned'), ('PROG', 'Programmer'), ('TEST', 'Tester'), ('MAN', 'Project manager'), ('ARCH', 'System architect'), ('ADMN', 'System administrator')], max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('REG', 'Regular employee'), ('MAN', 'Project manager')], default=users_app.models.UserRoles('Regular employee'), max_length=15),
        ),
    ]
