# Generated by Django 2.1.7 on 2019-03-17 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20190309_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('token', models.CharField(max_length=5)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2019, 3, 18, 22, 26, 58, 553662))),
            ],
        ),
    ]
