# Generated by Django 2.1.7 on 2019-03-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='default title', max_length=80),
            preserve_default=False,
        ),
    ]
