# Generated by Django 2.1.7 on 2019-03-27 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messages_app', '0001_initial'),
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentattachment',
            name='target_attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messages_app.Attachment'),
        ),
        migrations.AddField(
            model_name='commentattachment',
            name='target_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_app.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='attachments',
            field=models.ManyToManyField(through='events_app.CommentAttachment', to='messages_app.Attachment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_app.EventIdea'),
        ),
    ]
